
void setup() {
  // display image the really hard way
  for (int y = 0; y < h; y++) {
    for (int x = 0; x < w; x++) {
      int i = x + y * w; // indexing
      if (myImage[i] == true)
        stroke(255);
      else
        stroke(0);
      point(x, y);
    }
  }
}

// image size
int w = 64;
int h = 64;

// black and white (binary) image data
boolean[] myImage = { true,false,true,false,true,true,false,true,true,false,true,true,true,true,false,true,true,true,false,false,false,true,true,true,true,true,true,false,true,true,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,
true,false,false,true,false,false,true,false,true,false,true,false,false,true,true,false,false,true,false,false,true,true,true,true,false,true,false,true,false,false,true,true,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,
false,true,true,false,true,false,true,false,true,true,false,true,true,false,true,true,true,false,false,true,false,true,true,false,true,true,false,false,true,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,true,false,
false,false,false,false,true,false,true,false,false,true,true,false,true,true,true,false,true,true,false,true,false,false,false,true,false,false,true,false,true,false,true,false,true,false,false,true,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,
true,false,true,false,false,true,false,true,false,false,true,false,false,false,true,false,false,true,false,true,true,true,false,true,true,false,false,true,false,false,true,false,true,true,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,
false,false,false,false,false,false,false,false,false,false,false,true,true,false,true,true,false,true,true,false,false,false,true,false,false,true,true,false,true,true,false,true,true,false,true,false,true,true,true,false,false,true,false,false,true,false,false,false,false,true,false,false,false,true,false,true,false,true,false,false,false,true,false,false,
false,false,true,false,false,false,true,false,false,true,true,true,false,true,true,false,true,false,false,true,true,true,false,true,true,false,false,true,true,false,true,true,false,true,false,true,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,true,false,false,true,false,
false,false,false,true,false,false,false,false,true,false,false,true,true,false,true,false,true,true,false,false,false,true,false,false,true,true,true,false,true,true,false,true,true,true,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,true,false,true,false,false,false,
false,false,false,false,false,false,false,false,true,true,false,true,false,true,true,false,true,true,true,true,false,true,true,false,false,false,true,false,true,true,true,false,true,true,true,true,true,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,false,true,false,false,false,true,false,true,false,
true,false,false,true,false,false,true,true,false,true,true,false,true,false,true,false,false,true,false,true,false,false,true,true,true,true,false,true,false,true,true,true,true,false,false,true,true,false,false,true,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,
false,true,false,false,false,true,true,false,true,true,false,true,true,false,true,true,true,false,false,false,true,true,false,false,true,false,true,true,true,false,true,false,true,true,true,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,true,false,
true,false,true,true,false,false,true,true,false,true,false,true,false,true,false,false,true,true,true,false,false,true,true,false,false,true,true,false,true,true,false,true,true,false,true,true,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,true,
true,false,false,true,true,false,true,true,true,true,false,true,false,true,true,false,true,false,true,true,false,false,true,true,false,true,false,true,true,true,true,false,true,true,false,true,true,false,false,false,false,false,true,false,true,true,true,true,true,true,false,false,false,false,false,true,false,true,false,true,false,false,false,false,
true,false,true,false,true,true,false,false,false,true,false,true,true,false,true,false,true,true,false,false,true,true,false,true,true,false,true,true,false,true,true,true,false,true,true,false,true,false,false,false,true,true,true,true,true,true,false,true,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,
false,true,false,true,false,true,true,true,true,false,true,false,false,true,false,true,false,false,true,true,false,false,true,false,true,true,false,true,false,true,false,true,true,true,false,true,false,false,false,true,true,false,true,true,true,true,true,true,true,true,true,true,true,false,false,false,false,false,false,false,false,false,false,false,
true,false,true,false,true,false,false,false,true,false,true,false,true,false,false,false,true,false,false,false,true,false,false,false,false,true,false,true,true,true,false,true,false,true,true,true,false,true,false,true,true,true,false,true,true,false,true,true,true,false,true,true,true,true,false,false,false,false,false,false,false,false,false,false,
true,false,true,false,true,true,false,false,true,false,false,false,false,true,false,false,false,false,true,false,false,true,false,true,false,true,false,false,true,true,true,true,false,true,false,true,false,true,true,true,true,true,false,true,true,true,false,true,true,true,false,true,false,true,true,false,false,false,true,false,false,true,false,false,
false,true,false,true,false,false,true,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,false,false,true,true,false,true,true,true,false,false,false,true,false,true,false,true,true,true,true,false,true,false,false,false,false,false,false,false,true,
true,false,false,true,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,false,true,true,false,true,true,false,true,true,false,true,false,false,false,false,false,false,true,true,true,true,true,false,true,false,false,true,false,false,true,true,true,false,true,false,true,false,true,false,false,false,false,true,true,false,
false,true,false,false,false,true,false,true,false,true,false,false,false,false,false,false,true,true,false,false,false,true,false,false,false,true,false,false,true,false,true,false,true,false,false,true,false,true,false,true,true,true,true,false,false,false,true,false,false,true,true,false,true,true,true,false,true,false,false,false,false,false,false,true,
false,false,true,false,false,true,false,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,true,false,false,false,true,false,true,false,true,true,true,true,false,true,true,true,true,false,true,false,true,false,false,false,true,true,false,false,true,false,true,false,true,false,true,false,false,false,false,true,false,true,
false,false,false,true,false,true,true,true,true,false,true,false,false,false,true,false,true,false,false,true,false,false,false,true,false,true,false,true,false,true,false,false,true,false,false,true,false,true,true,true,true,true,false,false,false,true,false,false,true,true,true,true,false,true,false,true,false,false,false,false,false,false,true,false,
true,false,true,false,true,false,false,false,false,false,false,false,false,true,false,false,true,true,true,true,true,true,true,false,true,false,false,false,false,false,true,true,false,false,false,true,true,true,true,true,false,true,true,true,true,false,false,true,false,false,true,false,true,true,true,false,true,true,false,false,false,false,false,true,
false,false,false,false,false,true,false,true,false,true,false,false,false,false,true,false,false,true,false,true,false,true,true,true,true,true,true,true,true,true,false,true,false,false,true,true,false,true,false,true,true,false,true,false,true,true,false,true,true,true,false,true,false,true,false,true,false,false,false,false,false,false,false,false,
true,true,true,true,false,true,false,false,false,false,false,false,false,false,true,false,false,true,true,true,true,true,false,true,true,false,true,false,false,true,false,true,false,false,true,true,true,true,true,true,true,true,false,true,true,true,true,false,true,true,false,true,false,true,false,true,true,true,false,false,false,true,false,true,
false,true,false,true,false,true,true,true,true,false,true,false,false,false,false,true,false,false,false,false,false,true,true,true,false,true,true,true,true,true,true,false,true,false,true,false,true,false,true,true,false,true,true,false,true,false,true,true,false,false,true,true,true,true,false,false,false,false,false,true,false,false,false,false,
true,false,true,false,true,false,false,true,false,true,false,false,true,false,true,false,false,true,true,true,true,false,true,false,true,true,false,true,true,false,false,true,false,false,true,true,true,true,false,true,true,true,true,true,true,true,true,false,true,true,true,false,false,true,true,true,true,false,false,false,false,false,false,false,
true,true,false,true,false,true,false,true,false,true,true,false,false,false,false,true,true,false,false,true,false,true,true,true,false,true,true,false,false,true,false,true,false,true,false,true,true,true,true,true,false,true,true,false,true,false,true,true,false,true,true,true,false,false,true,false,true,false,false,true,false,false,false,false,
false,true,true,false,true,false,false,true,false,false,true,true,false,false,false,false,false,true,false,true,false,false,true,true,false,false,true,true,true,false,true,false,false,false,true,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,true,true,true,false,true,true,false,false,false,false,false,false,false,false,
true,false,false,true,false,true,false,true,true,false,false,true,false,false,false,false,false,false,false,false,true,false,false,true,true,true,false,false,true,false,false,true,true,false,false,false,true,true,true,true,true,true,true,true,true,false,true,false,true,true,false,true,true,true,false,false,true,false,false,false,true,false,false,false,
false,false,true,false,true,false,true,false,false,true,true,false,true,false,false,false,false,false,true,false,false,true,false,false,false,false,true,true,false,true,false,false,false,false,true,true,true,false,true,false,true,true,true,false,true,true,true,true,true,true,true,false,true,false,true,true,true,false,false,true,false,false,false,false,
true,false,true,false,true,false,true,true,false,false,true,false,true,false,false,false,false,false,false,false,true,false,false,true,false,false,false,true,false,false,true,false,false,false,false,true,true,true,true,true,true,true,true,true,true,false,true,false,true,true,true,false,true,true,false,false,true,false,false,false,true,true,false,false,
true,false,false,true,false,true,false,true,true,false,true,false,true,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,true,true,true,true,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,false,true,true,false,true,false,false,false,true,false,false,false,
false,false,true,false,true,false,true,false,true,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,true,false,true,true,false,true,true,true,true,true,false,true,true,true,true,true,false,true,true,true,false,true,false,false,false,false,false,true,true,false,false,
false,true,false,false,false,false,false,false,false,true,false,true,true,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,true,true,true,true,true,true,true,true,true,false,true,false,true,true,true,false,true,false,true,true,false,false,false,true,false,false,true,false,
false,false,true,false,true,false,true,true,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,true,true,true,true,true,false,true,false,false,false,false,true,true,false,false,
false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,true,true,false,true,true,true,true,true,true,true,true,true,true,true,true,false,true,false,true,true,false,true,false,false,false,false,false,true,false,true,
false,false,true,false,true,false,true,false,false,true,false,true,false,true,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,true,false,true,true,true,false,true,true,true,true,true,true,true,true,false,true,true,true,false,true,true,true,true,false,true,true,false,false,false,false,false,true,false,true,false,
true,false,false,false,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,true,true,true,true,true,true,true,true,false,true,true,true,true,false,true,true,false,true,true,false,true,false,false,true,false,false,false,false,false,true,false,false,
false,true,false,false,true,false,true,false,false,false,false,true,false,false,true,false,true,false,false,true,false,false,false,false,false,false,false,false,false,true,true,true,false,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,false,true,true,true,true,false,true,false,false,false,false,false,true,true,false,
false,false,false,false,false,false,false,true,false,false,false,false,true,false,false,false,false,true,false,false,false,false,true,false,true,false,false,false,false,false,true,true,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,false,true,false,true,false,true,false,false,false,false,false,false,false,false,false,
false,false,true,false,true,true,false,false,false,true,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,true,false,true,false,true,true,true,true,true,true,true,false,true,true,true,true,true,false,true,false,true,true,true,false,true,false,true,false,false,false,false,false,false,true,false,false,
true,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,false,true,true,false,true,true,true,true,true,true,false,true,true,true,true,true,false,true,false,true,true,false,false,false,false,false,false,false,false,false,false,
false,true,false,true,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,false,true,true,true,true,true,true,false,true,true,true,true,true,true,true,true,false,true,true,true,true,false,true,false,true,false,false,false,false,false,false,false,false,false,
false,false,false,false,true,false,false,false,false,false,true,false,false,true,false,true,false,false,true,false,false,false,false,false,true,false,false,false,false,true,false,true,true,false,true,true,true,true,true,true,false,true,true,true,false,true,true,true,false,true,false,true,false,true,false,false,false,false,false,false,false,false,false,false,
false,false,false,false,false,false,false,true,true,false,true,true,false,true,false,true,true,false,true,false,true,false,false,false,false,false,false,true,false,true,true,false,true,true,false,true,false,true,false,true,true,true,false,true,true,true,false,true,true,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,
false,false,true,false,true,false,true,false,false,true,false,false,true,false,true,false,false,false,true,false,true,false,true,false,false,true,false,false,false,false,false,true,false,true,true,false,true,true,true,true,true,true,true,true,true,true,true,true,false,true,true,false,true,false,false,false,false,true,false,false,false,false,false,false,
true,false,false,false,false,false,true,true,false,true,true,false,false,true,false,true,true,true,false,false,true,false,true,false,false,false,true,false,false,true,true,false,true,false,true,true,false,true,true,false,true,false,true,false,false,true,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,
false,true,false,true,false,true,false,true,false,false,true,true,false,true,false,false,false,true,true,false,true,false,true,true,false,false,true,false,false,false,false,true,true,false,false,true,false,false,true,true,true,false,true,true,false,true,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,
false,false,false,false,true,false,false,false,true,true,false,false,true,false,true,true,false,false,true,false,true,false,false,true,true,false,false,false,false,false,false,false,true,true,false,true,true,true,false,false,true,true,true,true,true,false,true,false,true,false,true,false,false,false,false,false,false,true,false,false,false,false,false,false,
true,false,true,false,false,true,true,true,false,true,true,false,true,false,true,false,true,true,false,true,false,true,false,true,false,true,true,false,false,false,false,false,false,true,false,true,false,false,true,true,true,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,
false,true,false,false,true,false,false,true,false,false,true,false,true,false,true,true,false,false,true,false,true,false,true,false,true,false,true,false,false,false,false,false,false,false,true,false,true,true,false,false,false,true,true,true,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,
false,false,true,false,false,true,false,true,true,false,true,false,true,false,false,true,true,true,false,true,false,true,false,true,true,false,false,true,false,false,false,false,false,false,false,false,false,true,true,true,false,false,true,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,
true,false,false,false,false,true,false,false,true,true,false,true,false,true,true,false,false,true,true,true,true,true,true,false,true,true,false,false,false,false,false,true,false,false,false,true,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,
false,false,false,false,false,false,true,true,false,false,true,false,true,false,true,true,true,false,false,false,true,false,false,true,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,
true,false,false,true,false,false,false,false,true,true,true,true,true,false,true,false,true,true,true,false,true,true,false,true,false,true,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,
false,true,false,false,false,false,false,false,false,false,true,false,true,true,false,true,false,true,true,false,true,false,true,false,true,false,false,true,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,
false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,true,false,false,true,false,true,false,false,true,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,
true,false,false,false,false,true,false,false,true,false,false,false,true,false,true,false,true,true,false,false,true,false,true,false,false,true,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,
false,false,true,false,false,false,false,false,false,true,false,false,true,false,false,false,false,true,true,false,false,true,false,false,true,false,true,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,true,
false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,true,false,true,false,true,true,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,true,true,true,true,true,false,true,
false,false,true,false,false,true,false,false,false,true,false,false,false,true,false,true,false,false,true,false,true,false,false,true,false,true,false,true,false,true,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,true,false,true,true,false,
true,false,false,true,false,false,false,false,false,false,false,true,false,true,false,false,true,false,true,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,true,false,false,true,false,false,false,false,false,false,false,true,true,true,false,true,false,true,true,true,true,false,true,true,
false,false,false,false,false,true,false,false,true,false,false,false,false,false,true,false,false,true,false,true,false,true,false,true,false,true,false,true,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,true,false,true,false,false,true,true,true,true,false,true,true,true,false,true


 
}; 

